# Generated by Django 5.0.1 on 2024-01-25 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('context', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('rating_popular', models.IntegerField(default=0)),
                ('date_of_create', models.DateTimeField()),
                ('author', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10)),
                ('context_of_comment', models.TextField()),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('date_of_create_comment', models.DateTimeField()),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_with_news.comment')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_with_news.news')),
            ],
        ),
    ]
